image: ubuntu

build:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq cmake cpio python3 python3-pip
    - pip3 install http://rscohn2.github.io/files/isrm.zip
    - isrm pkg install --activate-serial-number icc
    - source /opt/intel/bin/iccvars.sh -arch intel64
    - icc -v
    - mkdir build; cd build
    - FC=ifort CC=icc CXX=icpc cmake ../src
    - make

test:
  stage: test
  script:
  - make test
