language: c
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cpio python3 python3-pip
  - sudo pip3 install http://rscohn2.github.io/files/isrm.zip
  - sudo isrm pkg install --activate-serial-number icc

script:
  - source /opt/intel/bin/iccvars.sh -arch intel64
  - icc -v
  - mkdir build; cd build
  - FC=ifort CC=icc CXX=icpc cmake ../src
  - make
  - make test
