image: ubuntu

install:
  - sudo apt-get update -qq && apt-get install -y -qq cmake cpio python3 python3-pip
  - sudo pip3 install http://rscohn2.github.io/files/isrm-master.zip
  - sudo isrm pkg install --activate-serial-number icc ifort

test_script:
  - source /opt/intel/bin/iccvars.sh -arch intel64
  - icc -v
  - mkdir build; cd build
  - FC=ifort CC=icc CXX=icpc cmake ../src
  - make
  - make test

build: off
