# Test Pipeline for Azure Pipelines

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: sudo apt-get update -qq
  sudo isrm pkg install --activate-serial-number icc ifort
  displayName: 'Preinstall cleanup'

- script:  sudo apt-get install -qq -y cpio python3 python3-pip
  displayName: 'Install cpio, Python, pip'

- script: sudo pip3 install http://rscohn2.github.io/files/isrm-master.zip
  displayName: 'install isrm'

- script: sudo isrm pkg install --activate-serial-number icc ifort
  displayName: 'Activte license'

- script: |
     source /opt/intel/bin/iccvars.sh -arch intel64 &&
     icc -v &&
     mkdir build; cd build &&
     FC=ifort CC=icc CXX=icpc cmake ../src &&
     make &&
     make test
  displayName: 'Attempt compile'
