# Test Pipeline for Azure Pipelines
# Template for Linux

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: sudo apt-get update -qq
  displayName: 'Preinstall cleanup'

- script:  sudo apt-get install -qq -y cpio python3 python3-pip && pip3 install --upgrade setuptools
  displayName: 'Install cpio, Python, pip, setuptools'

- script: sudo pip3 install http://rscohn2.github.io/files/isrm-master.zip
  displayName: 'install isrm'

- task: GetLicense@1
  inputs:
    secureFile: psxe.lic

- script: sudo isrm pkg install icc ifort
  displayName: 'Activate license'

- script: |
     source /opt/intel/bin/iccvars.sh -arch intel64 &&
     icc -v &&
     mkdir build; cd build &&
     FC=ifort CC=icc CXX=icpc cmake ../src &&
     make &&
     make test
  displayName: 'Attempt compile'
